#!/usr/bin/env zsh

spacebar -m config clock                on
spacebar -m config power                on
spacebar -m config spacing_left         20
spacebar -m config right_shell          on
spacebar -m config power_icon_strip      
spacebar -m config right_shell_icon     
spacebar -m config right_shell_command  "$HOME/.config/spacebar/toggl.sh"

