mxid: '@houjun:matrix.jemoka.com'
device_id: QMYCKHFAKS
access_token: MDAxZmxvY2F0aW9uIG1hdHJpeC5qZW1va2EuY29tCjAwMTNpZGVudGlmaWVyIGtleQowMDEwY2lkIGdlbiA9IDEKMDAyY2NpZCB1c2VyX2lkID0gQGhvdWp1bjptYXRyaXguamVtb2thLmNvbQowMDE2Y2lkIHR5cGUgPSBhY2Nlc3MKMDAyMWNpZCBub25jZSA9IG5Dc2VjZVdVTn5mWVFmYUoKMDAyZnNpZ25hdHVyZSBCkHyaDl9nKZiqpt7iJhf5DIEvTxSufvgnUzuWe1_eHQo
homeserver: https://matrix.jemoka.com
room_cache_size: 32
room_cache_age: 60
notify_sound: true
send_to_verified_only: false
data_dir: /home/hliu/.local/share/gomuks
cache_dir: /home/hliu/.cache/gomuks
history_path: /home/hliu/.cache/gomuks/history.db
room_list_path: /home/hliu/.cache/gomuks/rooms.gob.gz
media_dir: /home/hliu/.cache/gomuks/media
download_dir: /home/hliu/Downloads
state_dir: /home/hliu/.cache/gomuks/state
