# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

source ~/.zprofile

# ?? but gpg works with this
export GPG_TTY=$(tty)

setopt autocd

alias c="clear"
alias l="ls"
alias vim="nvim"
set -o vi
bindkey jj vi-cmd-mode
alias tmux="tmux -2"
export ZSH_AUTOSUGGEST_STRATEGY="completion"
export CPLUS_INCLUDE_PATH="/usr/include/qt/:$CPLUS_INCLUDE_PATH"

export ZPLUG_HOME=~/.zplug/
export ZPLUG_REPOS=~/.zplug/repos/ 
export ZPLUG_LOADFILE=~/.zplug/packages.zsh
export ZPLUG_BIN=~/.zplug/bin
export ZPLUG_CACHE_DIR=~/.zplug/cache
export ZPLUG_ERROR_LOG=~/.zplug/.error_log
source ~/.zplug/init.zsh
# Plugins!
zplug romkatv/powerlevel10k, as:theme, depth:1
zplug zsh-users/zsh-autosuggestions
zplug "plugins/git", from:oh-my-zsh
# Fire!
if ! zplug check; then
    echo; zplug install
fi
zplug load

PATH="/home/hliu/.zplug/bin:/opt/resolve/bin/:/usr/local/sbin:/usr/local/bin:/usr/bin"
PATH="$HOME/.local/bin:$PATH"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
